const ActionTypes = {
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    TOGGLE_ALL_TODOS: 'TOGGLE_ALL_TODOS',
    UPDATE_DRAFT: 'UPDATE_DRAFT',
    START_EDITING_TODO: 'START_EDITING_TODO',
    STOP_EDITING_TODO: 'STOP_EDITING_TODO',
    EDIT_TODO: 'EDIT_TODO',
    DELETE_COMPLETED_TODOS: 'DELETE_COMPLETED_TODOS'
};

export default ActionTypes;